// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5If8Wj4a8HmVvdEOM7MfIvJSEpavVHjQ',
    appId: '1:1039837215865:android:a21bac852e46d7388628a8',
    messagingSenderId: '1039837215865',
    projectId: 'signin-7889f',
    storageBucket: 'signin-7889f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw3MQZM-VidTY-G3VuI9snNbJZQMgaNQw',
    appId: '1:1039837215865:ios:9c46441314a5e6318628a8',
    messagingSenderId: '1039837215865',
    projectId: 'signin-7889f',
    storageBucket: 'signin-7889f.appspot.com',
    androidClientId: '1039837215865-o90vmveec4h2edf8m8l30p04q6kf1lnv.apps.googleusercontent.com',
    iosClientId: '1039837215865-mi6jkkbb7b57fk8htnqnrori3lv3ljqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSignin',
  );

}